#spring.application.name=board-practice

server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardtest
    password: 1234
    username: boardtest
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: create